Repository Arisamiga/Mnemosyne, pull requests merged in 2023-09, with the labels that each got.

#1 Fixed typos
  README.md
  build/Mnemosyne.guide
  src/scan.c
Labels: documentation, enhancement

#2 Code Quality Fixes
  .gitignore
  .vscode/tasks.json
  aminet.readme
  build/Guide_Images/mnemosyne.iff
  build/Guide_Images/mnemosyne_back.iff
  build/Guide_Images/mnemosyne_folder_ready.iff
  build/Guide_Images/mnemosyne_menu.iff
  build/Guide_Images/mnemosyne_ready.iff
  build/Guide_Images/mnemosyne_result.iff
  build/Guide_Images/mnemosyne_scanning.iff
  build/Guide_Images/pressdrawer.iff
  build/Mnemosyne.guide
  images/mnemosyne.png
  images/mnemosyneG.png
  images/mnemosyne_Gresult.png
  images/mnemosyne_back.png
  images/mnemosyne_folder_ready.png
  images/mnemosyne_menu.png
  images/mnemosyne_ready.png
  images/mnemosyne_result.png
  images/mnemosyne_scanning.png
  images/pressdrawer.png
  src/aboutWin.c
  src/funcs.c
  src/funcs.h
  src/main.c
  src/scan.c
  src/window.c
Labels: enhancement

#3 Updated with Changelogs
  aminet.readme
Labels: documentation
